name: build

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      framework: 'net6.0'
      config: 'Release'
      output: './publish'
    steps:
    - name: initialize variables
      run: echo "repo=$(echo ${{github.repository}} | sed -e 's|.*/|/|g')" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: dotnet publish -c $config -f $framework -o $output
    - name: replace base url
      run: sed -i -e 's|<base href="/"/>|<base href="${{env.repo}}/">|g' ${{env.output}}/wwwroot/index.html
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ${{env.output}}/wwwroot
        publish_branch: pages
        enable_jekyll: false
